[project]
name = "iot-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sounddevice>=0.5.2",
    "pygame>=2.5.0",
    "numpy>=1.24.0",
]
